### ISSUE TITLE
Binary version for Windows and Linux.

### ISSUE THREAD

**Issue by curiosport** [elrumordelaluz/svg-spreact-cli#3]
Hi, I love this tool but I have problems to create a .exe version or a binary for Linux, I use this tool in a Go program but it is not feasible for me to install node.js on the target machine for several reasons.

Can you please create a multi platform binary?

**Comment by elrumordelaluz** [comment]
Hi @curiosport, thanks for open the _Issue_.
Any idea on how to fix this? Also, PR super welcome!

Thanks,

**Comment by elrumordelaluz** [comment]
@curiosport did you address it in some way?

**Comment by curiosport** [comment]
Yes, using `pkg` but it has some limitations.

1. You have to install `18.5.0` version of `node.js` either manually or using `nvm` as that is the maximum version that `pkg` supports and using a lower version usually gives incompatibility problems with `svg-spreact`.
If you are going to use `nvm`:
```
// You must first note your current version of node.js
node -v

nvm install 18.5.0
nvm use 18.5.0
```

2. Then install `pkg` https://github.com/vercel/pkg
`npm install -g pkg`

3. Install `svg-spreact`
`npm i -g svg-spreact-cli`

4. Open a command line in the directory where the `svg-spreact` package is installed:
```
//In my case this is my directory:
cd %APPDATA%\nvm\v18.5.0\node_modules\svg-spreact-cli

//And run the following:
set PKG_CACHE_PATH=D:\.pkg-cache
pkg cli.js
```
It will download some files to the `D:\.pkg-cache` folder and then compile 3 binaries for Linux, Windows and Mac.

5. Finally, revert to your default version, `x.x` is what you should have noted in the first step:
`nvm use x.x`
----
So far the binary works fine and I have generated sprites on Linux and Windows but when I run the command:
`svg-spreact.exe --version`

It prints a blank line and doesn't show the version, I don't know why.

**Comment by elrumordelaluz** [comment]
Super useful your comment @curiosport, thanks!
